### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by eutudb23** [francoisminh/Hackintosh-EliteDesk-800-G3-Mini-65W#2]
Hi,
Sorry, I wanted to ask if you have dual monitor setup and if yes, do your both monitor work at the same time.
On my end I cannot use dual monitors and I wanted to ask if you are able to. I'm currently on oS Catalina.
Thank you!

**Comment by francoisminh** [comment]
Hello,
Is your SMBios setted to MacMini 8,1 ? My first version of EFI was set to iMac 17,1. The SMBios in the EFI Folder for Kaby Lake is setted to MacMini 8,1 and dual monitor is working.

**Comment by eutudb23** [comment]
I have the HP with i5-6500 and currently I'm using the 17.1 smbios. So you're saying if I switch it to 8.1 it should work right ?
Thank you

**Comment by eutudb23** [comment]
Nvm, your solution worked like a charm!!
Changed to MacMini 8.1 SMBios, I got black screen at first but then it came up.
Thank you!
Awesome work!
